import { ChapterLabel } from '@/components/primitives';
import { TraceHandoff } from '@/components/system-trace';

export function Principles() {
  return <section id="principles" className="chapter principles section-pad"><ChapterLabel number="04" title="HOW I THINK"/>
    <div className="section-heading-row"><h2 className="display">Good systems.<br/><span className="muted">Clear decisions.</span></h2><p className="section-deck">The principles behind<br/>the implementation.</p></div>
    <div className="principle-list">
      <article className="principle"><div><span className="eyebrow">01 / SIMPLICITY</span><h3>Complex system.<br/>Simple interface.</h3><p>Keep the complexity behind the scenes. Give the person using it a clear next step.</p></div><svg viewBox="0 0 480 150" className="principle-diagram" role="img" aria-label="Multiple complex inputs join into one clear output"><g className="logic-input"><path d="M12 20H100V75H200M12 55H75V75H200M12 95H100V75H200M12 130H135V75H200"/></g><path className="logic-active" d="M200 75H442"/><circle cx="200" cy="75" r="8"/><rect x="436" y="69" width="12" height="12"/><text x="14" y="149">COMPLEXITY</text><text x="315" y="110">ONE CLEAR OUTPUT</text></svg></article>
      <article className="principle"><div><span className="eyebrow">02 / ITERATION</span><h3>Ship. Observe.<br/>Improve.</h3><p>Production is feedback. Let what happens after launch inform what comes next.</p></div><svg viewBox="0 0 480 150" className="principle-diagram" role="img" aria-label="Build, ship, observe, and iterate form a feedback loop"><path className="logic-active" d="M35 65H430V125H35V65"/><g className="logic-steps">{['BUILD','SHIP','OBSERVE','ITERATE'].map((s,i)=><g key={s}><circle cx={35+i*130} cy="65" r="6"/><text x={35+i*130} y="37" textAnchor="middle">{s}</text></g>)}</g></svg></article>
      <article className="principle"><div><span className="eyebrow">03 / RESILIENCE</span><h3>Design for<br/>the unexpected.</h3><p>Permission gates, cancellation, retries, and diagnostics belong in the architecture.</p></div><svg viewBox="0 0 480 150" className="principle-diagram" role="img" aria-label="An unavailable direct route is replaced with a fallback route"><path className="logic-failed" d="M25 50H220M265 50H445"/><path className="logic-active" d="M25 50H120V115H355V50H445"/><path className="logic-cross" d="m232 41 18 18m0-18-18 18"/><text x="187" y="143">FALLBACK / READY</text><circle cx="445" cy="50" r="6"/></svg></article>
    </div><div className="decision-case"><span className="eyebrow">HOW I THINK / TOM CASE STUDY</span><div className="decision-flow"><span><b>CONSTRAINT</b>CLOUD DEPENDENCY</span><i>↓</i><span><b>DECISION</b>LOCAL-FIRST DESIGN</span><i>↓</i><span><b>RESULT</b>PRIVATE, RESPONSIVE AI</span></div><small>Voice, context, permission, and diagnostics are the confirmed design language of TOM.</small></div><TraceHandoff label="PRINCIPLE → PRACTICE"/>
  </section>;
}
