import { ChapterLabel, ExternalLink, Label } from '@/components/primitives';
import { ProjectVisual } from '@/components/project-visual';
import { TraceHandoff } from '@/components/system-trace';
import { projects } from '@/data/portfolio';
import { ProjectXRay } from '@/components/project-xray';

export function Projects(){return <section id="projects" className="chapter projects"><div className="projects-heading"><ChapterLabel number="06" title="SELECTED WORK"/><div className="section-heading-row"><h2 className="display">Ideas, out<br/><span className="muted">in the world.</span></h2><Label>FOLLOW THE PRODUCTS ↓</Label></div></div><div className="projects-viewport"><div className="projects-track">{projects.map(project=><article className={`project-slide ${project.type}`} key={project.id} id={project.id}>
    <div className="project-product"><div className="project-route" aria-hidden="true">{project.number} / SHIPPED<span/><i/></div><ProjectVisual type={project.type}/><ProjectXRay type={project.type}/></div><div className="project-copy"><Label>{project.number} / {project.category}</Label><h3>{project.name}<span className="orange">.</span></h3><h4>{project.title}</h4><p>{project.description}</p><p className="project-detail">{project.detail}</p><div className="project-metric"><strong>{project.metric}</strong><span>{project.metricLabel}</span></div><Label className="project-tech">{project.tech}</Label><ExternalLink href={project.url}>{project.linkLabel ?? 'Visit live project'}</ExternalLink></div>
    </article>)}</div></div><div className="additional-work"><Label>ALSO BUILT</Label><details><summary>Reusable MERN authentication module <span>+</span></summary><p>Signup, login, logout, refresh tokens, password hashing, real-time email OTP, account lockout, and protected routes.</p></details></div><TraceHandoff label="PRODUCTS → OWNERSHIP"/></section>;}
